### ISSUE TITLE
关于数据集预处理的部分

### ISSUE THREAD

**Issue by junminchen** [PericlesHat/enhanced-GPDM#1]
请问数据集是如何预处理成168x4的shape的？
想问问从NASA的原数据如何到这一步直接用的，谢谢！

**Comment by PericlesHat** [comment]
你好，

我们对 NASA 数据集进行了特征工程和预处理，具体可以看我们的[论文（v3）](https://arxiv.org/abs/2212.01609)中的 2.7 节和 3.3 节。

**Comment by junminchen** [comment]
您好，

明白您的意思，您提到的这几个部分好像您有在代码中实现过，想问一下NASA原始数据的数据结构是如何变成您这个(168,4)shape的数据的？

Files:
B0005.mat	Data for Battery #5
B0006.mat	Data for Battery #6
B0007.mat	Data for Battery #7
B0018.mat	Data for Battery #18

Data Structure:
cycle:	top level structure array containing the charge, discharge and impedance operations
	type: 	operation  type, can be charge, discharge or impedance
	ambient_temperature:	ambient temperature (degree C)
	time: 	the date and time of the start of the cycle, in MATLAB  date vector format
	data:	data structure containing the measurements
	   for charge the fields are:
		Voltage_measured: 	Battery terminal voltage (Volts)
		Current_measured:	Battery output current (Amps)
		Temperature_measured: 	Battery temperature (degree C)
		Current_charge:		Current measured at charger (Amps)
		Voltage_charge:		Voltage measured at charger (Volts)
		Time:			Time vector for the cycle (secs)
	   for discharge the fields are:
		Voltage_measured: 	Battery terminal voltage (Volts)
		Current_measured:	Battery output current (Amps)
		Temperature_measured: 	Battery temperature (degree C)
		Current_charge:		Current measured at load (Amps)
		Voltage_charge:		Voltage measured at load (Volts)
		Time:			Time vector for the cycle (secs)
		Capacity:		Battery capacity (Ahr) for discharge till 2.7V 
	   for impedance the fields are:
		Sense_current:		Current in sense branch (Amps)
		Battery_current:	Current in battery branch (Amps)
		Current_ratio:		Ratio of the above currents 
		Battery_impedance:	Battery impedance (Ohms) computed from raw data
		Rectified_impedance:	Calibrated and smoothed battery impedance (Ohms) 
		Re:			Estimated electrolyte resistance (Ohms)
		Rct:			Estimated charge transfer resistance (Ohms)

**Comment by PericlesHat** [comment]
我们采用的是discharge这个档案作为评估，通过脚本收集原mat文件中的数据。这个`(168，4)`的形状代表我们从这个电池组中discharge档案采集到了168个时间步，后面的四个维度分别是State of Health（SOH，详见论文定义）以及三个手工特征，分别是温度的中点、电压的中点和电压的积分，论文3.3节中有详细定义。

**Comment by junminchen** [comment]
明白，所以说如果我想应用您的方法其他的数据，还需要将discharge部分的代码处理成您说的这个部分，谢谢。

**Comment by junminchen** [comment]
> 我们采用的是discharge这个档案作为评估，通过脚本收集原mat文件中的数据。这个`(168，4)`的形状代表我们从这个电池组中discharge档案采集到了168个时间步，后面的四个维度分别是State of Health（SOH，详见论文定义）以及三个手工特征，分别是温度的中点、电压的中点和电压的积分，论文3.3节中有详细定义。

还想请问一下您，这一部份数据处理的脚本有开源吗？以及要是没有的话，可以开源吗？

**Comment by PericlesHat** [comment]
我们计划在论文接收后开源这一部分。
